---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: testapi
  labels:
    svc: testapi
spec:
  selector:
    matchLabels:
      svc: testapi
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
    interval: 1s
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: testapi
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      svc: testapi
  resources:
    requests:
      memory: 400Mi
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: testapi-prom
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    prometheus: testapi
