apiVersion: v1
kind: Service
metadata:
  name: root
  labels:
    svc: testapi
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8887'
spec:
  ports:
  - name: query
    port: 8888
    protocol: TCP
  - name: metrics
    port: 8887
    protocol: TCP
  selector:
    run: root
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: root
  name: root
spec:
  replicas: 3
  selector:
    matchLabels:
      run: root
  template:
    metadata:
      labels:
        run: root
    spec:
      containers:
      - env:
        - name: UPSTREAM_URI
          value: 0.0.0.0:8888
        - name: DOWNSTREAM_URI
          value: http://branch:8888
        - name: SERVICE_NAME
          value: root 
        - name: REPORTER_URI
          value: http://zipkin:9411/api/v2/spans
        image: mcastelino/test-api-server:latest
        name: root
